FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
COPY subscriber.conf /etc/supervisor/
COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]
