FROM python:3.11

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y dos2unix && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

COPY subscriber.conf .
COPY start.sh .
RUN dos2unix start.sh && chmod +x start.sh

CMD ["/bin/bash", "start.sh"]
